services:

    postgres:
        image: postgres:17.6-alpine
        ports:
            - "5432:5432"
        networks:
            - app-network
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
        env_file:
            - env.list
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        restart: unless-stopped

    app:
        build: .
        ports:
            - "80:8080"
        networks:
            - app-network
        depends_on:
            - redis
            - postgres
        env_file:
            - env.list
        restart: unless-stopped

    redis:
        image: redis:alpine
        hostname: redis
        ports:
            - "6379:6379"
        networks:
            - app-network

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: celery -A app worker --loglevel=info
        depends_on:
            - postgres
            - redis
            - app
        volumes:
            - ./logs:/app/logs
        environment:
            DJANGO_SETTINGS_MODULE: app.settings
        env_file:
            - env.list
        networks:
            - app-network

    beat:
        build:
            context: .
            dockerfile: Dockerfile
        command: celery -A app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
        depends_on:
            - redis
            - postgres
        environment:
            DJANGO_SETTINGS_MODULE: app.settings
        env_file:
            - env.list
        networks:
            - app-network
        volumes:
            - ./celerybeat:/data
        restart: unless-stopped

networks:
    app-network:
        driver: bridge
