# Generated by Django 5.2.6 on 2025-09-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('paid', 'Paid'), ('lost', 'Lost')], default='new', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='lead_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadFollowupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('new', 'New'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('paid', 'Paid'), ('lost', 'Lost')], max_length=16)),
                ('delay', models.PositiveSmallIntegerField()),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'delay'], name='lead_rule_status_delay_idx')],
                'constraints': [models.UniqueConstraint(fields=('status', 'delay'), name='lead_rule_status_delay_uniq')],
            },
        ),
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('paid', 'Paid'), ('lost', 'Lost')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lead.lead')),
            ],
            options={
                'indexes': [models.Index(fields=['lead', '-created_at'], name='lead_event_latest_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='lead.lead')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='lead.leadfollowuprule')),
            ],
            options={
                'indexes': [models.Index(fields=['lead', '-created_at'], name='lead_followup_history_idx')],
            },
        ),
    ]
